version: "3"

services:
  nginx:
    image: nginx
    build: 
      context: ./requirements/nginx
      dockerfile: Dockerfile
    container_name: nginx
    restart: always
    depends_on:
      - wordpress
    ports:
      - 443:443
    volumes:
      - wp-volume:/var/www/html/wordpress
    networks:
      - docker_network
    env_file:
      - .env

  mariadb:
    image: mariadb
    build: 
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    container_name: mariadb
    restart: always
    expose:
      - "3306"
    volumes:
      - db-volume:/var/lib/mysql
    networks:
      - docker_network
    env_file:
      - .env

  wordpress:
      image: wordpress
      build:
        context: ./requirements/wordpress
        dockerfile: Dockerfile
      container_name: wordpress
      restart: always
      depends_on:
        - mariadb
      expose:
        - "9000"
      volumes:
        - wp-volume:/var/www/html/wordpress
      networks:
        - docker_network
      env_file:
        - .env

networks:
  docker_network:
    driver: bridge

volumes:
  wp-volume:
    driver_opts:
      type: none
      o: bind
      device: /home/ylabrahm/data/wordpress
  db-volume:
    driver_opts:
      type: none
      o: bind
      device: /home/ylabrahm/data/database
